CREATE TABLE IF NOT EXISTS users (
id TEXT PRIMARY KEY,
username TEXT UNIQUE NOT NULL,
email TEXT UNIQUE NOT NULL,
passwordHash TEXT NOT NULL,
avatarUrl TEXT,
coverUrl TEXT,
createdAt INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS videos (
id TEXT PRIMARY KEY,
userId TEXT NOT NULL,
title TEXT NOT NULL,
description TEXT,
thumbnailUrl TEXT,
videoUrl TEXT NOT NULL,
views INTEGER DEFAULT 0,
duration INTEGER,
isShort INTEGER DEFAULT 0,
createdAt INTEGER NOT NULL,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS comments (
id TEXT PRIMARY KEY,
videoId TEXT NOT NULL,
userId TEXT NOT NULL,
content TEXT NOT NULL,
parentId TEXT,
createdAt INTEGER NOT NULL,
FOREIGN KEY (videoId) REFERENCES videos(id) ON DELETE CASCADE,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (parentId) REFERENCES comments(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS likes (
userId TEXT NOT NULL,
videoId TEXT NOT NULL,
type TEXT CHECK(type IN ('LIKE', 'DISLIKE')),
PRIMARY KEY (userId, videoId),
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (videoId) REFERENCES videos(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS subscriptions (
subscriberId TEXT NOT NULL,
channelId TEXT NOT NULL,
createdAt INTEGER NOT NULL,
PRIMARY KEY (subscriberId, channelId),
FOREIGN KEY (subscriberId) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (channelId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS playlists (
id TEXT PRIMARY KEY,
userId TEXT NOT NULL,
name TEXT NOT NULL,
description TEXT,
isPrivate INTEGER DEFAULT 0,
createdAt INTEGER NOT NULL,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS playlistVideos (
playlistId TEXT NOT NULL,
videoId TEXT NOT NULL,
position INTEGER NOT NULL,
PRIMARY KEY (playlistId, videoId),
FOREIGN KEY (playlistId) REFERENCES playlists(id) ON DELETE CASCADE,
FOREIGN KEY (videoId) REFERENCES videos(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS watchHistory (
userId TEXT NOT NULL,
videoId TEXT NOT NULL,
watchedAt INTEGER NOT NULL,
PRIMARY KEY (userId, videoId),
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (videoId) REFERENCES videos(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS tags (
id TEXT PRIMARY KEY,
name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS videoTags (
videoId TEXT NOT NULL,
tagId TEXT NOT NULL,
PRIMARY KEY (videoId, tagId),
FOREIGN KEY (videoId) REFERENCES videos(id) ON DELETE CASCADE,
FOREIGN KEY (tagId) REFERENCES tags(id) ON DELETE CASCADE
);